apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ndo3xql4l-python 
  janus-idp.io/tekton: ndo3xql4l-python
  backstage.io/kubernetes-id: ndo3xql4l-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ndo3xql4l-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml